defaults:
  - _self_
  - hydra: default
  - wandb: default
  - override hydra/launcher: slurm

name: test
smoke_test: False

seed: 0
device: cpu
log_freq: 100

# Optimization process
epochs: 10
learning_rate: 0.001
batch_size: 128
max_pooling: False
sigmoid: True
stride: 3
latent_dim: 128
random_initial: True #Whether to initialise random weights. If set to False, make sure to specify path_weights, which should be the relative path to the model weights you want to initialise on!!!
path_weights: "" #e.g., "logs/test/runs/2026-02-12_11-36-31/model.pth"

dataloader_workers: 1
load_tiles: True # Whether to load tiles into memory
tiles_path: "/gws/nopw/j04/iecdt/deep_learning_lab/1km_naturalcolor_numpy"
train_metadata: "/gws/nopw/j04/iecdt/deep_learning_lab/1km_naturalcolor_metadata_time_train.csv"
val_metadata: "/gws/nopw/j04/iecdt/deep_learning_lab/1km_naturalcolor_metadata_time_val.csv"
train_rgb_stats: "/gws/nopw/j04/iecdt/deep_learning_lab/1km_naturalcolor_metadata_rgb_stats.npz"
